/* auto-generated by NAPI-RS */
/* eslint-disable */
/** List all currently connected USB devices. */
export declare function listDevices(): Array<UsbDevice>

/**
 * Stop the active USB device watcher.
 * The watcher thread will exit after the next event or on process exit.
 */
export declare function stopWatching(): void

export interface UsbDevice {
  vendorId: number
  productId: number
  manufacturer?: string
  product?: string
  serialNumber?: string
  deviceClass: number
  deviceSubclass: number
  deviceProtocol: number
  busId: string
  deviceAddress: number
}

export interface UsbEvent {
  eventType: UsbEventType
  device?: UsbDevice
  deviceId: string
  serialNumber?: string
}

export declare const enum UsbEventType {
  Connected = 'Connected',
  Disconnected = 'Disconnected'
}

/**
 * Start watching for USB device connect/disconnect events.
 * The callback receives `(err, event)` for each hotplug event.
 * Only one watcher can be active at a time.
 *
 * Events are debounced to coalesce USB re-enumeration sequences
 * (Connected -> Disconnected -> Connected) into a single event.
 * The optional `debounce_ms` parameter controls the window (default 500ms).
 */
export declare function watchDevices(callback: ((err: Error | null, arg: UsbEvent) => any), debounceMs?: number | undefined | null): void
