/* auto-generated by NAPI-RS */
/* eslint-disable */
/** List all currently connected USB devices. */
export declare function listDevices(): Array<UsbDevice>

/**
 * Stop the active USB device watcher.
 * The watcher thread will exit after the next event or on process exit.
 */
export declare function stopWatching(): void

export interface UsbDevice {
  vendorId: number
  productId: number
  manufacturer?: string
  product?: string
  serialNumber?: string
  /**
   * Raw `bDeviceClass` from the device descriptor. This is legitimately
   * `0x00` for HID and composite devices, which declare their class
   * per-interface. Inspect `interfaces` for the actual function class.
   */
  deviceClass: number
  deviceSubclass: number
  deviceProtocol: number
  busId: string
  deviceAddress: number
  /**
   * Interfaces in the device's active configuration. May be empty on
   * Windows for non-composite devices bound to a single driver.
   */
  interfaces: Array<UsbInterface>
}

export interface UsbEvent {
  eventType: UsbEventType
  device?: UsbDevice
  deviceId: string
  serialNumber?: string
}

export declare const enum UsbEventType {
  Connected = 'Connected',
  Disconnected = 'Disconnected'
}

/**
 * Summary information about a single USB interface, taken from the
 * interface descriptor of the device's active configuration.
 *
 * This is where the real device function class lives for HID and
 * composite devices (keyboards, trackpads, iPhones, etc.), whose
 * device-level `bDeviceClass` is `0x00` per the USB specification.
 */
export interface UsbInterface {
  interfaceNumber: number
  class: number
  subclass: number
  protocol: number
  interfaceString?: string
}

/**
 * Start watching for USB device connect/disconnect events.
 * The callback receives `(err, event)` for each hotplug event.
 * Only one watcher can be active at a time.
 *
 * Events are debounced to coalesce USB re-enumeration sequences
 * (Connected -> Disconnected -> Connected) into a single event.
 * The optional `debounce_ms` parameter controls the window (default 500ms).
 */
export declare function watchDevices(callback: ((err: Error | null, arg: UsbEvent) => any), debounceMs?: number | undefined | null): void
